[book]
src = "src"
title = "Fjord Token Staking"

[output.html]
no-section-label = true
additional-js = ["solidity.min.js"]
additional-css = ["book.css"]
git-repository-url = "https://github.com/marigoldlabs/fjord-token"

[output.html.fold]
enable = true
