name: Fjord Staking CI

on: push


env:  
  ETHEREUM_RPC: ${{ secrets.ETHEREUM_RPC }}

jobs:
  test-unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run unit tests
        run: make test-unit
  
  test-integration:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run integration tests
        run: make test-integration

  test-invariant:
    name: Invariant tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run invariant tests
        run: make test-invariant

  test-fuzz:
    name: Fuzz tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run fuzz tests
        run: make test-fuzz
      
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      # forge converage cannot check internal functions issue:
      - name: Generate the coverage report using the unit and the invariant tests
        run: |
          make coverage

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "./lcov.info"

      - name: Add coverage summary
        run: |
          echo "## Coverage result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Uploaded to Codecov" >> $GITHUB_STEP_SUMMARY
